# Generated by Django 5.2.3 on 2025-06-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='isCompletd',
            new_name='isCompleted',
        ),
    ]
